// Anthony Wilcox licenses this file to you under the GPL license.
// See the LICENSE file in the project root for more information.

// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("0.0.1906.1104")]
[assembly: AssemblyFileVersion("0.0.1906.1104")]